Badge update
razor-network/validators pull request #9
Opened 2022-11-27 15:44 UTC by thesoze

2022-11-28 05:30 UTC, yohanelly95 approved these changes

2022-11-28 05:32 UTC, yohanelly95 requested changes

2022-11-28 05:32 UTC, yohanelly95 commented on chains/razorSChain/validatorList.json
>  	}
please add a coma to line 57.

2022-11-28 17:27 UTC, thesoze commented on chains/razorSChain/validatorList.json
>  	}
Comma was added

2022-11-29 09:24 UTC, SkandaBhat approved these changes

2022-11-29 09:24 UTC, SkandaBhat commented
@yohanelly95 Please check and approve

2022-11-30 09:42 UTC, yohanelly95 approved these changes

2022-11-30 09:42 UTC, merged